[global]
   workgroup = WORKGROUP
   server string = HueMedia
   netbios name = HUEMEDIA
   security = user
   map to guest = Bad User
   guest account = nobody
   dns proxy = no
   log level = 0
   load printers = no
   printing = bsd
   disable spoolss = yes
   socket options = TCP_NODELAY IPTOS_LOWDELAY

[MUSIC]
   comment = HueMedia Music Pool
   path = /pool/Music
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   force user = hue
   veto files = /lost+found/.Trashes/.Trash-$recycle.bin/
   delete veto files = yes

[SYSTEM]
   comment = HueMedia System (read-only)
   path = /opt/hue-media
   browseable = yes
   read only = yes
   guest ok = no
   valid users = hue
