[General]
Name = HueMedia
Class = 0x200414
DiscoverableTimeout = 0
PairableTimeout = 0
AutoEnable = true

[Policy]
AutoEnable = true
ReconnectUUIDs = 0000110e-0000-1000-8000-00805f9b34fb;0000110b-0000-1000-8000-00805f9b34fb
ReconnectAttempts = 10
ReconnectIntervals = 1,2,4,8,16,32,64

[GATT]
Cache = no

[AVRCP]
VolumeControl = true
PlayerApplicationSettings = true
AbsoluteVolume = true
